### ISSUE TITLE
FixBrightness min/max values?

### ISSUE THREAD

**Issue by Selur** [OpusGang/bore#5]
What are the min/max values for thrlo, thrhi , step?

**Comment by Selur** [comment]
Got any link to libgsl-28.dll ? [The link inside the README](https://www.gnu.org/software/gsl/) doesn't seem to offer compiled libraries, only the source code.
Alternatively, a static build of libbore which includes the library would be nice too. :)

**Comment by noizuy** [comment]
> What are the min/max values for thrlo, thrhi , step?

0/1, 0/1, 1/no max. If this is for some GUI, I'd suggest waiting a bit, since FixBrightness is gonna be removed soon and Balance is gonna be renamed.

> Got any link to libgsl-28.dll ? [The link inside the README](https://www.gnu.org/software/gsl/) doesn't seem to offer compiled libraries, only the source code. Alternatively, a static build of libbore which includes the library would be nice too. :)

Check the new actions.

**Comment by Selur** [comment]
> Check the new actions.

Nice, thanks!

> 0/1, 0/1, 1/no max. If this is for some GUI, I'd suggest waiting a bit, since FixBrightness is gonna be removed soon and Balance is gonna be renamed.

Ah, okay. I'll wait then. :)

**Comment by Selur** [comment]
>  If this is for some GUI, I'd suggest waiting a bit, since FixBrightness is gonna be removed soon and Balance is gonna be renamed.

Any news on that, since atm. I only get:
```
Python exception: There is no function named FixBrightness
```
when using:
```
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/DeringFilter/Bore/libbore.dll")
clip = core.bore.FixBrightness(clip, top=2, bottom=2, left=2, right=2)
```
and calling:
```
clip = core.text.Text(clip, text="\n".join(dir(core.bore)) )
```
shows:
```
Filteredne
SinglePlane
SinglePlaneDebug
SinglePlaneLimited
SinglePlaneWeighted
```
and I expected  'FixBrightness' and 'Balance'.

=> does not seem like the filter can be used atm. in Vapoursynth.

**Comment by noizuy** [comment]
> ```
> clip = core.text.Text(clip, text="\n".join(dir(core.bore)) )
> ```
> 
> shows:
> 
> ```
> Filteredne
> SinglePlane
> SinglePlaneDebug
> SinglePlaneLimited
> SinglePlaneWeighted
> ```
> 
> and I expected 'FixBrightness' and 'Balance'.

Looks to me like you might've accidentally grabbed a build from newstuff thinking it was master, @Selur. I have no idea what "Filteredne" might be, though. On my end:
```py
>>> print(dir(vs.core.bore))
['MultiPlane', 'SinglePlane', 'SinglePlaneDebug', 'SinglePlaneLimited', 'SinglePlaneWeighted']
```

**Comment by Selur** [comment]
Since the usage states:
`core.bore.FixBrightness(clip clip, int top=0, int bottom=0, int left=0, int right=0, clip ignore_mask=None, float thrlo=0.1, float thrhi=8.0, int step=1, int plane=0)`
shouldn't there be  'FixBrightness' and 'Balance' ?

**Comment by noizuy** [comment]
If you're using a newstuff build, which you seem to be doing, you should be referencing the README from that branch: https://github.com/OpusGang/bore/blob/newstuff/README.md

**Comment by Selur** [comment]
Ahhh,... I missed that the README changed.
Thanks :)
